<?php

use App\Branch;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class BranchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                "name" => "Central Office",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => true,
                "branch_head_id" => 0,
                "code" => "000",
            ],
            [
                "name" => "Kaloocan City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "001",
            ],
            [
                "name" => "City of Manila",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "002",
            ],
            [
                "name" => "Pasay City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "003",
            ],
            [
                "name" => "Quezon City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "004",
            ],
            [
                "name" => "Las Pinas City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "005",
            ],
            [
                "name" => "Makati City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "006",
            ],
            [
                "name" => "Malabon",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "007",
            ],
            [
                "name" => "Mandaluyong City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "008",
            ],
            [
                "name" => "Marikina",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "009",
            ],
            [
                "name" => "Parañaque City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "010",
            ],
            [
                "name" => "Pasig",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "011",
            ],
            [
                "name" => "San Juan",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "012",
            ],
            [
                "name" => "Valenzuela City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "013",
            ],
            [
                "name" => "Muntinlupa City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "014",
            ],
            [
                "name" => "Bangued, Abra",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "015",
            ],
            [
                "name" => "La Trinidad, Benguet",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "016",
            ],
            [
                "name" => "Bontoc, Mt. Province",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "017",
            ],
            [
                "name" => "Baguio City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "018",
            ],
            [
                "name" => "Lamut, Ifugao",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "019",
            ],
            [
                "name" => "Tabuk, Kalinga-Apayao",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "020",
            ],
            [
                "name" => "Laoag City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "021",
            ],
            [
                "name" => "Laoag, Ilocos Norte",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "022",
            ],
            [
                "name" => "Province of Ilocos Norte, Batac Branch",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "023",
            ],
            [
                "name" => "Vigan, Ilocos Sur",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "024",
            ],
            [
                "name" => "San Fernando, La Union",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "025",
            ],
            [
                "name" => "Lingayen, Pangasinan",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "026",
            ],
            [
                "name" => "Province of Pangasinan, Alaminos Branch",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "027",
            ],
            [
                "name" => "Pangasinan, Tayug Branch",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "028",
            ],
            [
                "name" => "Dagupan City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "029",
            ],
            [
                "name" => "San Carlos City, Pangasinan",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "030",
            ],
            [
                "name" => "Basco, Batanes",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "031",
            ],
            [
                "name" => "Tuguegarao, Cagayan",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "032",
            ],
            [
                "name" => "Cagayan, Tuao Branch",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "033",
            ],
            [
                "name" => "Cagayan, Sanchez Mira Branch",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "034",
            ],
            [
                "name" => "Ilagan, Isabela",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "035",
            ],
            [
                "name" => "Province of Nueva Vizcaya",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "036",
            ],
            [
                "name" => "Cabarroguis, Quirino",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "037",
            ],
            [
                "name" => "Balanga, Bataan",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "038",
            ],
            [
                "name" => "Province of Bulacan (Guiguinto)",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "039",
            ],
            [
                "name" => "Province of Bulacan, Meycauayan Branch",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "040",
            ],
            [
                "name" => "Cabanatuan, Nueva Ecija",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "041",
            ],
            [
                "name" => "San Fernando, Pampanga",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "042",
            ],
            [
                "name" => "Province of Tarlac",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "043",
            ],
            [
                "name" => "Iba, Zambales",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "044",
            ],
            [
                "name" => "Angeles City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "045",
            ],
            [
                "name" => "Cabanatuan City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "046",
            ],
            [
                "name" => "Olongapo City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "047",
            ],
            [
                "name" => "San Jose City, Nueva Ecija",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "048",
            ],
            [
                "name" => "Palayan City, Nueva Ecija",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "049",
            ],
            [
                "name" => "Province of Nueva Ecija, Talavera Branch",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "050",
            ],
            [
                "name" => "Province of Aurora",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "051",
            ],
            [
                "name" => "Batangas City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "052",
            ],
            [
                "name" => "Batangas , Batangas",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "053",
            ],
            [
                "name" => "Batangas, Lemery Branch",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "054",
            ],
            [
                "name" => "Province of Batangas, Nasugbu Branch",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "OSS",
            ],
            [
                "name" => "Batangas, Tanauan Branch",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "056",
            ],
            [
                "name" => "Province of Cavite",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "057",
            ],
            [
                "name" => "Sta. Cruz, Laguna",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "058",
            ],
            [
                "name" => "Laguna, Siniloan Branch",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "0S9",
            ],
            [
                "name" => "Province of Laguna,CaIamba Branch",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "060",
            ],
            [
                "name" => "Boac, Marinduque",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "061",
            ],
            [
                "name" => "Mamburao,Mindoro Occidental",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "062",
            ],
            [
                "name" => "Mindoro Occidental, San Jose",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "063",
            ],
            [
                "name" => "Calapan, Mindoro Oriental",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "064",
            ],
            [
                "name" => "Province of Palawan",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "065",
            ],
            [
                "name" => "Province of Quezon",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "066",
            ],
            [
                "name" => "Quezon, Infanta Branch",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "067",
            ],
            [
                "name" => "Province of Rizal",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "068",
            ],
            [
                "name" => "Rizal, Morong Branch",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "069",
            ],
            [
                "name" => "Romblon, Romblon",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "070",
            ],
            [
                "name" => "Cavite City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "071",
            ],
            [
                "name" => "Lipa City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "072",
            ],
            [
                "name" => "Lucena City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "073",
            ],
            [
                "name" => "Puerto Princesa City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "074",
            ],
            [
                "name" => "San Pablo City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "07S",
            ],
            [
                "name" => "Tagaytay City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "076",
            ],
            [
                "name" => "Trece Martirez City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "077",
            ],
            [
                "name" => "Province of Albay",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "078",
            ],
            [
                "name" => "Province of Camarines Norte",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "079",
            ],
            [
                "name" => "Province of Camarines Sur",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "080",
            ],
            [
                "name" => "Virac, Catanduanes",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "081",
            ],
            [
                "name" => "Masbate, Masbate",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "082",
            ],
            [
                "name" => "Sorsogon, Sorsogon",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "083",
            ],
            [
                "name" => "lriga City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "084",
            ],
            [
                "name" => "Legaspi City, Albay",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "085",
            ],
            [
                "name" => "Naga City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "086",
            ],
            [
                "name" => "Province of Aklan",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "087",
            ],
            [
                "name" => "San Jose, Antique",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "088",
            ],
            [
                "name" => "Roxas, Capiz",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "089",
            ],
            [
                "name" => "IIoiIo, IIoiIo",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "090",
            ],
            [
                "name" => "Province of Negros Occidental",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "091",
            ],
            [
                "name" => "Bacolod City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "092",
            ],
            [
                "name" => "Bago City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "093",
            ],
            [
                "name" => "Cadiz City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "094",
            ],
            [
                "name" => "IIoiIo City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "095",
            ],
            [
                "name" => "La Carlota City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "096",
            ],
            [
                "name" => "Roxas City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "097",
            ],
            [
                "name" => "San Carlos City (Negros)",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "098",
            ],
            [
                "name" => "Silay City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "099",
            ],
            [
                "name" => "Guimaras",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "100",
            ],
            [
                "name" => "Province of Bohol (Tagbilaran)",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "101",
            ],
            [
                "name" => "Cebu Province, Cebu",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "102",
            ],
            [
                "name" => "Province of Negros Oriental (Dumaguete Province)",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "103",
            ],
            [
                "name" => "Larena, Siquijor",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "104",
            ],
            [
                "name" => "Bais City, Negros Occidental",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "105",
            ],
            [
                "name" => "Canlaon City, Negros Oriental",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "106",
            ],
            [
                "name" => "Cebu City, Cebu",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "107",
            ],
            [
                "name" => "Danao City, Cebu",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "108",
            ],
            [
                "name" => "Dumaguete City (Negros Oriental)",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "109",
            ],
            [
                "name" => "Lapu-Lapu City, Cebu",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "110",
            ],
            [
                "name" => "Mandaue City, Cebu",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "111",
            ],
            [
                "name" => "Tagbilaran City, Bohol",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "OSS",
            ],
            [
                "name" => "Toledo City, Cebu",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "113",
            ],
            [
                "name" => "Borongan, Eastern Samar",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "114",
            ],
            [
                "name" =>
                "Leyte Province (Palo, Northern Leyte)                                            ",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "115",
            ],
            [
                "name" => "Catarman, Northern Samar",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "116",
            ],
            [
                "name" => "Maasin, Southern Leyte",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "117",
            ],
            [
                "name" => "Catbalogan Province, Western Samar",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "118",
            ],
            [
                "name" => "Catbalogan City, Western Samar",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "119",
            ],
            [
                "name" => "Calbayog City, Western Samar",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "120",
            ],
            [
                "name" => "Ormoc City, Leyte",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "121",
            ],
            [
                "name" => "Tacloban City, Northern Leyte",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "122",
            ],
            [
                "name" => "Biliran, Biliran",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "123",
            ],
            [
                "name" => "Isabela, Basilan",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "124",
            ],
            [
                "name" => "Jolo, Sulu",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "125",
            ],
            [
                "name" => "Bonga, Tawi-Tawi",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "126",
            ],
            [
                "name" => "Province of Zamboanga del Norte",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "127",
            ],
            [
                "name" => "Dipolog City, Zamboanga del Norte",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "128",
            ],
            [
                "name" => "Zamboanga City, Zamboanga",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "129",
            ],
            [
                "name" => "Province of Zamboanga del Sur",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "130",
            ],
            [
                "name" => "Pagadian City, Zamboanga del Sur",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "131",
            ],
            [
                "name" => "Dapitan City, Zamboanga del Norte",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "132",
            ],
            [
                "name" => "Malaybalay, Bukidnon",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "133",
            ],
            [
                "name" => "Mambajao, Camiguin",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "134",
            ],
            [
                "name" => "Province of Misamis Occidental (Oroquieta)",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "135",
            ],
            [
                "name" => "Cagayan de Oro Province, Misamis Oriental",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "136",
            ],
            [
                "name" => "Cagayan de Oro City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "137",
            ],
            [
                "name" => "Gingoog City, Misamis Oriental",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "138",
            ],
            [
                "name" => "Oroquieta City, Misamis Occidental",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "139",
            ],
            [
                "name" => "Ozamis City, Misamis Occidental",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "140",
            ],
            [
                "name" => "Tangub City, Misamis Occidental",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "141",
            ],
            [
                "name" => "Province of Davao del Norte (Tagum City)",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "142",
            ],
            [
                "name" => "Mati, Davao Oriental",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "143",
            ],
            [
                "name" => "Digos, Davao del Sur",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "144",
            ],
            [
                "name" => "Koronadal, South Cotabato",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "145",
            ],
            [
                "name" => "Davao City, Davao del Sur",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "146",
            ],
            [
                "name" => "Gen Santos City, South Cotabato",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "147",
            ],
            [
                "name" => "Alabel, Saranggani",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "148",
            ],
            [
                "name" => "Tubod, Lanao del Norte",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "149",
            ],
            [
                "name" => "Province of Lanao del Sur",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "150",
            ],
            [
                "name" => "Province of Maguindanao",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "151",
            ],
            [
                "name" => "Cotabato Province (Kidapawan)",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "152",
            ],
            [
                "name" => "Isulan, Sultan Kudarat",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "153",
            ],
            [
                "name" => "Cotabato City, Maguindanao",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "154",
            ],
            [
                "name" => "Iligan City, Lanao Del Norte",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "155",
            ],
            [
                "name" => "Marawi City, Lanao del Sur",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "156",
            ],
            [
                "name" => "Butuan City, Agusan del Norte",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "157",
            ],
            [
                "name" => "Province of Agusan del Norte",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "158",
            ],
            [
                "name" => "Prosperidad, Agusan del Sur",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "159",
            ],
            [
                "name" => "Province of Surigao del Norte",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "160",
            ],
            [
                "name" => "Tandag, Surigao del Sur",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "161",
            ],
            [
                "name" => "Surigao City, Surigao del Norte",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "162",
            ],
            [
                "name" => "Antipolo City, Rizal",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "163",
            ],
            [
                "name" => "Taguig City, Metro Manila",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "164",
            ],
            [
                "name" => "Santiago City, Isabela",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "165",
            ],
            [
                "name" => "Kabankalan City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "166",
            ],
            [
                "name" => "Province of Cavite, Bacoor City Branch",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "167",
            ],
            [
                "name" => "Bogo City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "168",
            ],
            [
                "name" => "Province of Apayao (Luna)",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "OSS",
            ],
            [
                "name" => "Biñan City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "170",
            ],
            [
                "name" => "Urdaneta City",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "171",
            ],
            [
                "name" => "Santa Rosa City, Laguna",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "172",
            ],
            [
                "name" => "KioskCO",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "501",
            ],
            [
                "name" => "PS Bank Kiosk",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "504",
            ],
            [
                "name" => "LBP - Region 12 Extension Office",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "534",
            ],
            [
                "name" => "Amicassa  - Region 7 Extension Office",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "535",
            ],
            [
                "name" => "Province  of Cavite (Trece Martire z)",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "057",
            ],
            [
                "name" => "Self Service Registration",
                "created_at" => "2024-07-03",
                "updated_at" => "2024-07-03",
                "is_main_branch" => false,
                "branch_head_id" => 0,
                "code" => "600",
            ],
        ];

        // Schema::disableForeignKeyConstraints();
        // Branch::truncate();
        // Schema::enableForeignKeyConstraints();

        foreach ($data as $value) {
            Branch::create($value);
        }
    }
}
