#!/bin/bash
# Cleanup script: Remove public HRIS artifacts from private-payroll frontend
BASE="/home/gab/Desktop/Private HRIS/private-payroll/pr-frontend/src"

# 1. Delete government form views
rm -f "$BASE/Views/BIR_Form_2305.vue"
rm -f "$BASE/Views/GSIS_Member_Info.vue"
rm -f "$BASE/Views/PhilHealth_PMRF.vue"
rm -f "$BASE/Views/PagIbig_MDF.vue"
echo "✓ Deleted government form views"

# 2. Delete COS Payroll (Contract of Service - government)
rm -rf "$BASE/Views/COS_Payroll"
rm -rf "$BASE/components/COS_Payroll"
echo "✓ Deleted COS Payroll"

# 3. Delete public-sector Payroll Benefits views
rm -rf "$BASE/Views/Payroll_Benefits/Loyalty_Award"
rm -rf "$BASE/Views/Payroll_Benefits/RATA_Payroll"
rm -rf "$BASE/Views/Payroll_Benefits/Hazard_Pay"
rm -rf "$BASE/Views/Payroll_Benefits/Hazzard_Pay"
rm -rf "$BASE/Views/Payroll_Benefits/Monetization_Payroll"
rm -rf "$BASE/Views/Payroll_Benefits/Payroll-Communication Macco"
rm -rf "$BASE/Views/Payroll_Benefits/Retirement_Benefits"
rm -rf "$BASE/Views/Payroll_Benefits/Uniform_and_ClothingAllowance"
echo "✓ Deleted public benefits views"

# 4. Delete public-sector Benefits components
rm -rf "$BASE/components/Payroll_Benefits/Hazard_Pay"
rm -rf "$BASE/components/Payroll_Benefits/Loyalty_Award"
rm -rf "$BASE/components/Payroll_Benefits/Monetization_Payroll"
rm -rf "$BASE/components/Payroll_Benefits/Payroll_CommunicationMacco"
rm -rf "$BASE/components/Payroll_Benefits/RATA_Payroll"
rm -rf "$BASE/components/Payroll_Benefits/Uniform_and_ClothingAllowance"
echo "✓ Deleted public benefits components"

# 5. Delete public-sector Report views
rm -f "$BASE/Views/Payroll_Reports/rptGSISRemittance.vue"
rm -f "$BASE/Views/Payroll_Reports/rptLoyaltyAward.vue"
rm -f "$BASE/Views/Payroll_Reports/rptMonetizationPayroll.vue"
rm -f "$BASE/Views/Payroll_Reports/rptRataPayroll.vue"
rm -f "$BASE/Views/Payroll_Reports/rptSBSISTENCE.vue"
rm -f "$BASE/Views/Payroll_Reports/rptSUBSISTENCE.vue"
rm -f "$BASE/Views/Payroll_Reports/rptLandbankTextReport.vue"
rm -f "$BASE/Views/Payroll_Reports/rptAtmLetterLandbank.vue"
rm -f "$BASE/Views/Payroll_Reports/rptHazardPay.vue"
rm -f "$BASE/Views/Payroll_Reports/rptHazzardPay.vue"
rm -f "$BASE/Views/Payroll_Reports/rptUniform&ClothingAllowance.vue"
rm -f "$BASE/Views/Payroll_Reports/rptPayrollCommunicationMacco.vue"
rm -f "$BASE/Views/Payroll_Reports/rptATMMidYearBonus.vue"
rm -f "$BASE/Views/Payroll_Reports/rptMidYearIndividualVoucher.vue"
rm -f "$BASE/Views/Payroll_Reports/rptMidYearVoucher.vue"
rm -f "$BASE/Views/Payroll_Reports/rptMidYearBonusHub.vue"
echo "✓ Deleted public-sector report views"

# 6. Delete public-sector Composables
COMP="$BASE/Composables"
rm -f "$COMP/useCOSPayroll.js"
rm -f "$COMP/useCOSPayrollPeriods.js"
rm -f "$COMP/useGSISMemberInfo.js"
rm -f "$COMP/useGSISRemittance.js"
rm -f "$COMP/useHazardPay.js"
rm -f "$COMP/useHazardPayReport.js"
rm -f "$COMP/useLoyaltyAward.js"
rm -f "$COMP/useLoyaltyAwardBenefits.js"
rm -f "$COMP/useMonetizationPayroll.js"
rm -f "$COMP/useMonetizationPayrollReport.js"
rm -f "$COMP/useRATAPayroll.js"
rm -f "$COMP/useRATAPayrollReport.js"
rm -f "$COMP/useRetirementBenefits.js"
rm -f "$COMP/useSUBSISTENCE.js"
rm -f "$COMP/useUniformClothingAllowance.js"
rm -f "$COMP/useUniformClothingAllowanceReport.js"
rm -f "$COMP/useReimbursementCommunication.js"
rm -f "$COMP/useReimbursementCommunicationReport.js"
rm -f "$COMP/useAtmLetterLandbank.js"
rm -f "$COMP/useLandbankTextReport.js"
rm -f "$COMP/useBIRForm2305.js"
rm -f "$COMP/usePagIbigMDF.js"
rm -f "$COMP/usePhilHealthPMRF.js"
rm -f "$COMP/useATMMidYearBonus.js"
rm -f "$COMP/useMidYearIndividualVoucher.js"
echo "✓ Deleted public-sector composables"

echo ""
echo "All public HRIS artifacts removed successfully."
